import { Injectable, UnauthorizedException, ConflictException, Inject } from '@nestjs/common';
import * as bcrypt from 'bcryptjs';
import * as jwt from 'jsonwebtoken';
import { User } from '../../domain/entities/user.entity';
import type { IUserRepository } from '../../domain/repositories/user.repository.interface';
import type { ITokenBlacklistRepository } from '../../domain/repositories/token-blacklist.repository.interface';
import { LoginDto, RegisterDto, AuthResponseDto } from '../../interfaces/presenters/auth.dto';
import { JwtPayload } from '../../infrastructure/auth/jwt.strategy';

@Injectable()
export class AuthService {
    private readonly jwtSecret = process.env.JWT_SECRET || 'defaultsecret';
    private readonly jwtExpiresIn = '24h';

    constructor(
        @Inject('IUserRepository') private readonly userRepository: IUserRepository,
        @Inject('ITokenBlacklistRepository')
        private readonly tokenBlacklistRepository: ITokenBlacklistRepository,
    ) {}

    async register(registerDto: RegisterDto): Promise<AuthResponseDto> {
        // Normalize email to lowercase
        const normalizedEmail = registerDto.email.toLowerCase();

        // Check if user already exists
        const existingUser = await this.userRepository.findByEmail(normalizedEmail);
        if (existingUser) {
            // Generieke foutmelding om account enumeration te voorkomen
            // Gebruik generieke melding die niet verraadt of account bestaat
            throw new ConflictException('Unable to complete registration');
        }

        // Hash password
        const hashedPassword = await bcrypt.hash(registerDto.passwordHash, 10);
        const newUser = new User(
            '', // ID will be generated by MongoDB
            normalizedEmail,
            hashedPassword,
            registerDto.firstName,
            registerDto.lastName,
            [], // skills
            [], // interests
            [], // favorites
            false, // twoFactorEnabled
            new Date(),
            new Date(),
            '', // studyProgram
            0, // yearOfStudy
            '', // studyLocation
            0, // studyCredits
            '', // twoFactorSecret
            '', // refreshToken
        );

        const savedUser = await this.userRepository.create(newUser);

        // Generate JWT token
        const payload: JwtPayload = { email: savedUser.email, sub: savedUser._id };
        const accessToken = jwt.sign(payload, this.jwtSecret, {
            expiresIn: this.jwtExpiresIn,
        });

        return {
            access_token: accessToken,
            user: {
                firstName: savedUser.firstName,
                lastName: savedUser.lastName,
                email: savedUser.email,
            },
        };
    }

    async login(loginDto: LoginDto): Promise<AuthResponseDto> {
        // Normalize email to lowercase
        const normalizedEmail = loginDto.email.toLowerCase();

        // Account enumeration bescherming: altijd dezelfde operaties uitvoeren
        // om timing attacks te voorkomen
        const user = await this.userRepository.findByEmail(normalizedEmail);

        // Altijd password hash vergelijken, ook als gebruiker niet bestaat
        // Dit voorkomt timing verschillen tussen bestaande en niet-bestaande accounts
        const dummyHash = '$2a$10$dummyhashfordummycomparisonpurposesonly';
        const hashToCompare = user?.passwordHash || dummyHash;

        // Password verificatie altijd uitvoeren voor consistente timing
        const isPasswordValid = user
            ? await bcrypt.compare(loginDto.passwordHash, hashToCompare)
            : await bcrypt.compare(loginDto.passwordHash, dummyHash);

        // Generieke foutmelding om account enumeration te voorkomen
        if (!user || !isPasswordValid) {
            throw new UnauthorizedException('Invalid credentials');
        }

        // Generate JWT token
        const payload: JwtPayload = { email: user.email, sub: user._id };
        const accessToken = jwt.sign(payload, this.jwtSecret, {
            expiresIn: this.jwtExpiresIn,
        });

        return {
            access_token: accessToken,
            user: {
                firstName: user.firstName,
                lastName: user.lastName,
                email: user.email,
            },
        };
    }

    async validateUser(
        email: string,
        password: string,
    ): Promise<Omit<User, 'passwordHash'> | null> {
        const user = await this.userRepository.findByEmail(email);
        if (user && (await bcrypt.compare(password, user.passwordHash))) {
            const { passwordHash: userPasswordHash, ...result } = user;
            return result;
        }
        return null;
    }

    async validateUserById(userId: string): Promise<User | null> {
        return await this.userRepository.findById(userId);
    }

    verifyToken(token: string): JwtPayload {
        try {
            return jwt.verify(token, this.jwtSecret) as JwtPayload;
        } catch {
            throw new UnauthorizedException('Invalid token');
        }
    }

    async invalidateToken(token: string): Promise<void> {
        try {
            const payload = this.verifyToken(token);
            const decoded = jwt.decode(token) as { exp?: number };
            const expiresAt = decoded.exp
                ? new Date(decoded.exp * 1000)
                : new Date(Date.now() + 24 * 60 * 60 * 1000);
            await this.tokenBlacklistRepository.addToken(token, expiresAt);
        } catch (error) {
            // Als token niet valide is, hoeven we het niet toe te voegen aan blacklist
            // maar we gooien geen error om logout altijd te laten slagen
        }
    }

    async isTokenBlacklisted(token: string): Promise<boolean> {
        return await this.tokenBlacklistRepository.isTokenBlacklisted(token);
    }
}
