import {
    Injectable,
    UnauthorizedException,
    ConflictException,
    Inject,
    NotFoundException,
} from '@nestjs/common';
import * as bcrypt from 'bcryptjs';
import * as jwt from 'jsonwebtoken';
import { User, UserFavorite } from '../../domain/entities/user.entity';
import type { IUserRepository } from '../../domain/repositories/user.repository.interface';
import { LoginDto, RegisterDto } from '../../interfaces/presenters/auth.dto';
import { ModuleService } from './module.service';
import { Module } from '../../domain/entities/module.entity';

@Injectable()
export class AuthService {
    private readonly jwtSecret = process.env.JWT_SECRET || 'defaultsecret';
    private readonly jwtExpiresIn = '24h';

    constructor(
        @Inject('IUserRepository') private readonly userRepository: IUserRepository,
        private readonly moduleService: ModuleService,
    ) {}

    async register(registerDto: RegisterDto): Promise<{ access_token: string; user: any }> {
        // Normalize email to lowercase
        const normalizedEmail = registerDto.email.toLowerCase();

        // Check if user already exists
        const existingUser = await this.userRepository.findByEmail(normalizedEmail);
        if (existingUser) {
            throw new ConflictException('User with this email already exists');
        }

        // Hash password
        const hashedPassword = await bcrypt.hash(registerDto.passwordHash, 10);
        const newUser = new User(
            '', // ID will be generated by MongoDB
            normalizedEmail,
            hashedPassword,
            registerDto.firstName,
            registerDto.lastName,
            [], // skills
            [], // interests
            [], // favorites
            false, // twoFactorEnabled
            new Date(),
            new Date(),
            '', // studyProgram
            0, // yearOfStudy
            '', // studyLocation
            0, // studyCredits
            '', // twoFactorSecret
            '', // refreshToken
        );

        const savedUser = await this.userRepository.create(newUser);

        // Generate JWT token
        const payload = { email: savedUser.email, sub: savedUser._id };
        const access_token = jwt.sign(payload, this.jwtSecret, {
            expiresIn: this.jwtExpiresIn,
        });

        return {
            access_token,
            user: {
                firstName: savedUser.firstName,
                lastName: savedUser.lastName,
                email: savedUser.email,
            },
        };
    }

    async login(loginDto: LoginDto): Promise<{ access_token: string; user: any }> {
        // Normalize email to lowercase
        const normalizedEmail = loginDto.email.toLowerCase();
        // Find user by email
        const user = await this.userRepository.findByEmail(normalizedEmail);
        if (!user) {
            throw new UnauthorizedException('Invalid credentials');
        }

        // Verify password
        const isPasswordValid = await bcrypt.compare(loginDto.passwordHash, user.passwordHash);
        if (!isPasswordValid) {
            throw new UnauthorizedException('Invalid credentials');
        }

        // Generate JWT token
        const payload = { email: user.email, sub: user._id };
        const access_token = jwt.sign(payload, this.jwtSecret, {
            expiresIn: this.jwtExpiresIn,
        });

        return {
            access_token,
            user: {
                firstName: user.firstName,
                lastName: user.lastName,
                email: user.email,
            },
        };
    }

    async validateUser(email: string, password: string): Promise<any> {
        const user = await this.userRepository.findByEmail(email);
        if (user && (await bcrypt.compare(password, user.passwordHash))) {
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            const { passwordHash: userPasswordHash, ...result } = user;
            return result;
        }
        return null;
    }

    async validateUserById(userId: string): Promise<User | null> {
        return await this.userRepository.findById(userId);
    }

    verifyToken(token: string): any {
        try {
            return jwt.verify(token, this.jwtSecret);
        } catch {
            throw new UnauthorizedException('Invalid token');
        }
    }

    async getFavorites(userId: string): Promise<Module[]> {
        const user = await this.userRepository.findById(userId);
        if (!user) {
            throw new NotFoundException('User not found');
        }
        const modulePromises = user.favorites.map((favorite) =>
            this.moduleService.findById(favorite.moduleId),
        );
        const modules = await Promise.all(modulePromises);
        return modules.filter((module): module is Module => module !== null);
    }

    async addFavorite(userId: string, moduleId: string): Promise<void> {
        const user = await this.userRepository.findById(userId);
        if (!user) {
            throw new NotFoundException('User not found');
        }

        // Check if favorite already exists
        const existingFavorite = user.favorites.find((fav) => fav.moduleId === moduleId);
        if (existingFavorite) {
            return; // Already a favorite, no need to add again
        }

        // Get module to get module name
        const module = await this.moduleService.findById(moduleId);
        if (!module) {
            throw new NotFoundException('Module not found');
        }

        const favorite = new UserFavorite(moduleId, new Date(), module.name);

        await this.userRepository.addFavorite(userId, favorite);
    }

    async removeFavorite(userId: string, moduleId: string): Promise<void> {
        const user = await this.userRepository.findById(userId);
        if (!user) {
            throw new NotFoundException('User not found');
        }
        await this.userRepository.removeFavorite(userId, moduleId);
    }
}
